const CONSTANTS = {
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
  RESET: "RESET",
  SAVE: "SAVE",
  CHANGE: "CHANGE",
  UPDATE_LIST: "UPDATE_LIST",
  SAVE_LIST: "SAVE_LIST"
};

export default CONSTANTS;
